# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ba6c9cd915386703628fe65540dab1c29ea623fb24efdda81a41f56fe5c69cae18678cd5e82e18b6d0baedd2ba79400aee91f31c59eb1e387f39e16dffc3e93

test:
  secret_key_base: 1058082002797f9b89f1c095972e443406799be574c983bcc0ecac80bef2cb6bf24158d34eb26558f6cd5b506806377cda14b447b903e0d1e47f7b652d8bb722

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
